In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv(r"../data\raw\emi_prediction_dataset.csv")

pd.set_option('display.max_columns', None)  # Show all columns in the DataFrame
pd.set_option('display.max_rows', None)     # Show all rows in the DataFrame

df.shape

C:\Users\Suba\AppData\Local\Temp\ipykernel_832\1990976983.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"../data\raw\emi_prediction_dataset.csv")

(404800, 27)

In [3]:
df.head()

,age,gender,marital_status,education,monthly_salary,employment_type,years_of_employment,company_type,house_type,monthly_rent,family_size,dependents,school_fees,college_fees,travel_expenses,groceries_utilities,other_monthly_expenses,existing_loans,current_emi_amount,credit_score,bank_balance,emergency_fund,emi_scenario,requested_amount,requested_tenure,emi_eligibility,max_monthly_emi
0,38.0,Female,Married,Professional,82600.0,Private,0.9,Mid-size,Rented,20000.0,3,2,0.0,0.0,7200.0,19500.0,13200.0,Yes,23700.0,660.0,303200.0,70200.0,Personal Loan EMI,850000.0,15,Not_Eligible,500.0
1,38.0,Female,Married,Graduate,21500.0,Private,7.0,MNC,Family,0.0,2,1,5100.0,0.0,1400.0,5400.0,3500.0,Yes,4100.0,714.0,92500.0,26900.0,E-commerce Shopping EMI,128000.0,19,Not_Eligible,700.0
2,38.0,Male,Married,Professional,86100.0,Private,5.8,Startup,Own,0.0,4,3,0.0,0.0,10200.0,19400.0,6000.0,No,0.0,650.0,672100.0,324200.0,Education EMI,306000.0,16,Eligible,27775.0
3,58.0,Female,Married,High School,66800.0,Private,2.2,Mid-size,Own,0.0,5,4,11400.0,0.0,6200.0,11900.0,7900.0,No,0.0,685.0,440900.0,178100.0,Vehicle EMI,304000.0,83,Eligible,16170.0
4,48.0,Female,Married,Professional,57300.0,Private,3.4,Mid-size,Family,0.0,4,3,9400.0,21300.0,3600.0,16200.0,8100.0,No,0.0,770.0,97300.0,28200.0,Home Appliances EMI,252000.0,7,Not_Eligible,500.0

In [4]:
df.head()

,age,gender,marital_status,education,monthly_salary,employment_type,years_of_employment,company_type,house_type,monthly_rent,family_size,dependents,school_fees,college_fees,travel_expenses,groceries_utilities,other_monthly_expenses,existing_loans,current_emi_amount,credit_score,bank_balance,emergency_fund,emi_scenario,requested_amount,requested_tenure,emi_eligibility,max_monthly_emi
0,38.0,Female,Married,Professional,82600.0,Private,0.9,Mid-size,Rented,20000.0,3,2,0.0,0.0,7200.0,19500.0,13200.0,Yes,23700.0,660.0,303200.0,70200.0,Personal Loan EMI,850000.0,15,Not_Eligible,500.0
1,38.0,Female,Married,Graduate,21500.0,Private,7.0,MNC,Family,0.0,2,1,5100.0,0.0,1400.0,5400.0,3500.0,Yes,4100.0,714.0,92500.0,26900.0,E-commerce Shopping EMI,128000.0,19,Not_Eligible,700.0
2,38.0,Male,Married,Professional,86100.0,Private,5.8,Startup,Own,0.0,4,3,0.0,0.0,10200.0,19400.0,6000.0,No,0.0,650.0,672100.0,324200.0,Education EMI,306000.0,16,Eligible,27775.0
3,58.0,Female,Married,High School,66800.0,Private,2.2,Mid-size,Own,0.0,5,4,11400.0,0.0,6200.0,11900.0,7900.0,No,0.0,685.0,440900.0,178100.0,Vehicle EMI,304000.0,83,Eligible,16170.0
4,48.0,Female,Married,Professional,57300.0,Private,3.4,Mid-size,Family,0.0,4,3,9400.0,21300.0,3600.0,16200.0,8100.0,No,0.0,770.0,97300.0,28200.0,Home Appliances EMI,252000.0,7,Not_Eligible,500.0

In [5]:
df.tail()

,age,gender,marital_status,education,monthly_salary,employment_type,years_of_employment,company_type,house_type,monthly_rent,family_size,dependents,school_fees,college_fees,travel_expenses,groceries_utilities,other_monthly_expenses,existing_loans,current_emi_amount,credit_score,bank_balance,emergency_fund,emi_scenario,requested_amount,requested_tenure,emi_eligibility,max_monthly_emi
404795,27.0,Male,Married,Graduate,32400.0,Private,5.0,Large Indian,Rented,10400.0,4,3,2800.0,7000.0,2200.0,4900.0,6100.0,No,0.0,649.0,62000.0,32600.0,Personal Loan EMI,506000.0,47,Not_Eligible,500.0
404796,38.0,Male,Married,Post Graduate,49200.0,Private,1.9,MNC,Own,0.0,5,4,14000.0,0.0,2600.0,13600.0,8600.0,No,0.0,712.0,142200.0,38100.0,Personal Loan EMI,708000.0,33,Not_Eligible,5200.0
404797,32.0,Male,Single,Graduate,25700.0,Private,3.2,MNC,Rented,6300.0,1,0,0.0,0.0,2000.0,4600.0,2500.0,No,0.0,676.0,191600.0,39700.0,Home Appliances EMI,93000.0,21,High_Risk,5665.0
404798,48.0,Male,Married,Graduate,47200.0,Private,3.0,MNC,Own,0.0,4,3,0.0,0.0,7000.0,8900.0,7200.0,No,0.0,784.0,170400.0,45600.0,Home Appliances EMI,144000.0,36,Eligible,14460.0
404799,38.0,FEMALE,Married,Graduate,34900.0,Private,1.2,MNC,Family,0.0,2,1,0.0,0.0,4800.0,8100.0,2100.0,No,0.0,641.0,214400.0,99400.0,Home Appliances EMI,77000.0,35,Eligible,8756.0

In [6]:
df[["emi_eligibility", "max_monthly_emi"]].head(30)

   emi_eligibility  max_monthly_emi
0     Not_Eligible           500.00
1     Not_Eligible           700.00
2         Eligible         27775.00
3         Eligible         16170.00
4     Not_Eligible           500.00
5     Not_Eligible           500.00
6     Not_Eligible          1950.00
7     Not_Eligible          8260.00
8     Not_Eligible          5500.00
9     Not_Eligible          9355.50
10    Not_Eligible          8870.40
11    Not_Eligible           500.00
12        Eligible         13440.00
13    Not_Eligible          3083.85
14        Eligible         27360.00
15    Not_Eligible           500.00
16    Not_Eligible          4060.00
17    Not_Eligible          4273.50
18    Not_Eligible           500.00
19    Not_Eligible          5920.00
20    Not_Eligible          1694.00
21        Eligible         13002.00
22    Not_Eligible           500.00
23    Not_Eligible          1764.00
24        Eligible         14520.00
25        Eligible         25140.00
26    Not_Eligible          6230.00
27        Eligible         28620.00
28    Not_Eligible         21184.00
29    Not_Eligible           500.00

personal,ecommerce,home appliances => not eligible
max monthly emi => small amount like below 10,000 => not eligible

In [15]:
df.isnull().sum()

age                          0
gender                       0
marital_status               0
education                 2404
monthly_salary               0
employment_type              0
years_of_employment          0
company_type                 0
house_type                   0
monthly_rent              2426
family_size                  0
dependents                   0
school_fees                  0
college_fees                 0
travel_expenses              0
groceries_utilities          0
other_monthly_expenses       0
existing_loans               0
current_emi_amount           0
credit_score              2420
bank_balance              2426
emergency_fund            2351
emi_scenario                 0
requested_amount             0
requested_tenure             0
emi_eligibility              0
max_monthly_emi              0
dtype: int64

In [7]:
df.columns

Index(['age', 'gender', 'marital_status', 'education', 'monthly_salary',
       'employment_type', 'years_of_employment', 'company_type', 'house_type',
       'monthly_rent', 'family_size', 'dependents', 'school_fees',
       'college_fees', 'travel_expenses', 'groceries_utilities',
       'other_monthly_expenses', 'existing_loans', 'current_emi_amount',
       'credit_score', 'bank_balance', 'emergency_fund', 'emi_scenario',
       'requested_amount', 'requested_tenure', 'emi_eligibility',
       'max_monthly_emi'],
      dtype='object')

In [20]:
# see for cat columns otherwise num columns give lengthy output
for col in [
    'age', 'gender', 'marital_status', 'education', 
    'employment_type','company_type',
    'house_type', 'family_size',
    'dependents',
    'existing_loans',
    'emi_scenario','emi_eligibility',
]:
    
    print(f"\n===== {col} =====")
    print(df[col].value_counts(dropna=False))

===== age =====
age
38.0    120508
32.0    100424
48.0     80388
27.0     59852
58.0     40408
37.0       490
39.0       480
33.0       445
31.0       393
49.0       320
47.0       297
28.0       230
26.0       211
59.0       183
57.0       168
NaN          3
Name: count, dtype: int64

===== gender =====
gender
Male      237427
Female    158351
MALE        1865
M           1843
male        1815
F           1171
female      1165
FEMALE      1163
Name: count, dtype: int64

===== marital_status =====
marital_status
Married    307837
Single      96963
Name: count, dtype: int64

===== education =====
education
Graduate         181015
Post Graduate    100314
High School       60732
Professional      60335
NaN                2404
Name: count, dtype: int64

===== employment_type =====
employment_type
Private          283099
Government        81167
Self-employed     40534
Name: count, dtype: int64

===== company_type =====
company_type
Large Indian    121139
MNC             101409
Mid-size        101301
Startup          60706
Small            20245
Name: count, dtype: int64

===== house_type =====
house_type
Rented    161601
Own       142307
Family    100892
Name: count, dtype: int64

===== family_size =====
family_size
3    142856
2    100381
4     92409
1     38613
5     30541
Name: count, dtype: int64

===== dependents =====
dependents
2    142856
1    100381
3     92409
0     38613
4     30541
Name: count, dtype: int64

===== existing_loans =====
existing_loans
No     243227
Yes    161573
Name: count, dtype: int64

===== emi_scenario =====
emi_scenario
Home Appliances EMI        80988
Personal Loan EMI          80980
E-commerce Shopping EMI    80948
Education EMI              80942
Vehicle EMI                80942
Name: count, dtype: int64

===== emi_eligibility =====
emi_eligibility
Not_Eligible    312868
Eligible         74444
High_Risk        17488
Name: count, dtype: int64

In [8]:
df[["education", "monthly_rent", "credit_score", "bank_balance",
"emergency_fund"]].head(10)

       education  monthly_rent  credit_score bank_balance  emergency_fund
0   Professional       20000.0         660.0     303200.0         70200.0
1       Graduate           0.0         714.0      92500.0         26900.0
2   Professional           0.0         650.0     672100.0        324200.0
3    High School           0.0         685.0     440900.0        178100.0
4   Professional           0.0         770.0      97300.0         28200.0
5    High School       13500.0         792.0     260800.0         55600.0
6    High School           0.0         741.0      68000.0         36200.0
7  Post Graduate           0.0         623.0     184600.0         61700.0
8   Professional           0.0         712.0     235600.0         81800.0
9  Post Graduate           0.0         681.0     963200.0        519100.0

In [9]:
df[['house_type']].head(20)

   house_type
0      Rented
1      Family
2         Own
3         Own
4      Family
5      Rented
6         Own
7      Family
8      Family
9      Family
10     Family
11     Rented
12     Rented
13        Own
14     Family
15     Rented
16        Own
17     Family
18     Rented
19        Own

In [9]:
#  checking dirty values
df[['age', 'monthly_salary']].head(20)

     age monthly_salary
0   38.0        82600.0
1   38.0        21500.0
2   38.0        86100.0
3   58.0        66800.0
4   48.0        57300.0
5   38.0        38800.0
6   58.0        27100.0
7   58.0       392044.0
8   58.0        47700.0
9   32.0       129200.0
10  32.0        58600.0
11  38.0        47000.0
12  32.0        11837.0
13  48.0        53900.0
14  27.0       110800.0
15  48.0        64000.0
16  38.0        46600.0
17  27.0        77400.0
18  32.0        40700.0
19  38.0        47500.0

In [5]:
df["monthly_salary_raw"] = df["monthly_salary"]

df["monthly_salary"] = pd.to_numeric(
    df["monthly_salary"],
    errors="coerce"
)

dirty_salary_rows = df[
    df["monthly_salary"].isna() &
    df["monthly_salary_raw"].notna()
]

dirty_salary_rows[
    ["monthly_salary_raw"]
].value_counts()

dirty_salary_rows.head(20)

Empty DataFrame
Columns: [age, gender, marital_status, education, monthly_salary, employment_type, years_of_employment, company_type, house_type, monthly_rent, family_size, dependents, school_fees, college_fees, travel_expenses, groceries_utilities, other_monthly_expenses, existing_loans, current_emi_amount, credit_score, bank_balance, emergency_fund, emi_scenario, requested_amount, requested_tenure, emi_eligibility, max_monthly_emi, monthly_salary_raw]
Index: []

In [3]:
invalid_salary = df.loc[
    pd.to_numeric(
        df["monthly_salary"],
        errors="coerce"
    ).isna(),
    "monthly_salary"
]

invalid_salary.value_counts()

monthly_salary
18000.0.0      34
20000.0.0      16
23400.0.0      11
14400.0.0      11
26000.0.0       9
50500.0.0       9
19500.0.0       9
58600.0.0       8
32200.0.0       8
15000.0.0       8
48000.0.0       8
61800.0.0       7
27000.0.0       7
46500.0.0       7
52300.0.0       7
38800.0.0       7
45000.0.0       7
40300.0.0       7
31900.0.0       6
57700.0.0       6
54300.0.0       6
41900.0.0       6
39700.0.0       6
37500.0.0       6
57500.0.0       6
31800.0.0       6
29600.0.0       6
39000.0.0       6
82400.0.0       6
69200.0.0       6
41600.0.0       6
42000.0.0       6
34000.0.0       6
37100.0.0       6
31700.0.0       6
42600.0.0       6
34400.0.0       6
50100.0.0       6
43400.0.0       6
33300.0.0       5
16000.0.0       5
22900.0.0       5
73400.0.0       5
42500.0.0       5
35600.0.0       5
24700.0.0       5
36500.0.0       5
71600.0.0       5
27800.0.0       5
54400.0.0       5
30000.0.0       5
23800.0.0       5
59500.0.0       5
62900.0.0       5
55000.0.0       5
43700.0.0       5
62700.0.0       5
22500.0.0       5
29300.0.0       5
67800.0.0       5
27400.0.0       5
69400.0.0       5
57800.0.0       5
47500.0.0       5
48900.0.0       5
47200.0.0       5
57200.0.0       5
43500.0.0       5
51500.0.0       5
48500.0.0       5
46700.0.0       5
44400.0.0       5
48600.0.0       4
40600.0.0       4
46900.0.0       4
26100.0.0       4
79500.0.0       4
51600.0.0       4
51800.0.0       4
38600.0.0       4
63300.0.0       4
77300.0.0       4
27100.0.0       4
65300.0.0       4
62100.0.0       4
74200.0.0       4
92300.0.0       4
34500.0.0       4
39300.0.0       4
61500.0.0       4
37400.0.0       4
58500.0.0       4
56700.0.0       4
62200.0.0       4
24500.0.0       4
36100.0.0       4
12000.0.0       4
84500.0.0       4
52100.0.0       4
61200.0.0       4
43300.0.0       4
28300.0.0       4
73200.0.0       4
36400.0.0       4
36600.0.0       4
68700.0.0       4
63000.0.0       4
68800.0.0       4
37600.0.0       4
50800.0.0       4
48300.0.0       4
29100.0.0       4
33800.0.0       4
61600.0.0       4
51100.0.0       4
37900.0.0       4
46400.0.0       4
39500.0.0       4
39800.0.0       4
64900.0.0       4
61900.0.0       4
40900.0.0       4
41300.0.0       4
87800.0.0       4
42400.0.0       4
44200.0.0       4
37800.0.0       4
60500.0.0       4
22100.0.0       4
41700.0.0       4
46600.0.0       4
42200.0.0       4
49400.0.0       4
56500.0.0       4
35200.0.0       4
59700.0.0       4
32400.0.0       4
60200.0.0       4
55500.0.0       4
52900.0.0       4
70700.0.0       4
36900.0.0       3
63900.0.0       3
29000.0.0       3
61400.0.0       3
89800.0.0       3
58400.0.0       3
20700.0.0       3
67500.0.0       3
35800.0.0       3
30700.0.0       3
74800.0.0       3
53300.0.0       3
38300.0.0       3
32900.0.0       3
68100.0.0       3
43200.0.0       3
66300.0.0       3
111300.0.0      3
50200.0.0       3
68200.0.0       3
66800.0.0       3
84100.0.0       3
21200.0.0       3
54500.0.0       3
46200.0.0       3
32800.0.0       3
57900.0.0       3
35500.0.0       3
35400.0.0       3
75900.0.0       3
32300.0.0       3
47300.0.0       3
53700.0.0       3
35100.0.0       3
28900.0.0       3
40700.0.0       3
39100.0.0       3
69300.0.0       3
55900.0.0       3
24600.0.0       3
93900.0.0       3
68300.0.0       3
33700.0.0       3
55700.0.0       3
48700.0.0       3
53500.0.0       3
99500.0.0       3
74700.0.0       3
52600.0.0       3
83600.0.0       3
25300.0.0       3
29700.0.0       3
38400.0.0       3
59800.0.0       3
28000.0.0       3
62400.0.0       3
61300.0.0       3
56100.0.0       3
34700.0.0       3
25700.0.0       3
39900.0.0       3
20500.0.0       3
60300.0.0       3
41000.0.0       3
18100.0.0       3
23700.0.0       3
49500.0.0       3
25900.0.0       3
91300.0.0       3
65900.0.0       3
36200.0.0       3
60400.0.0       3
41500.0.0       3
87300.0.0       3
37000.0.0       3
22000.0.0       3
91700.0.0       3
66600.0.0       3
90800.0.0       3
68000.0.0       3
94800.0.0       3
33100.0.0       3
38500.0.0       3
64600.0.0       3
29400.0.0       3
59900.0.0       3
45100.0.0       3
72400.0.0       3
70100.0.0       3
32700.0.0       3
45600.0.0       3
27300.0.0       3
78500.0.0       3
96900.0.0       3
38900.0.0       3
68600.0.0       3
89200.0.0       3
67900.0.0       3
44800.0.0       3
24200.0.0       3
57100.0.0       3
41800.0.0       3
69000.0.0       3
15600.0.0       3
42300.0.0       3
52400.0.0       3
60900.0.0       3
42900.0.0       3
91400.0.0       3
52000.0.0       3
26400.0.0       3
30300.0.0       3
44600.0.0       3
29500.0.0       3
27900.0.0       3
41100.0.0       3
45900.0.0       3
30900.0.0       3
96700.0.0       3
26300.0.0       3
40500.0.0       3
27500.0.0       3
28600.0.0       3
53800.0.0       3
49900.0.0       3
33600.0.0       3
23200.0.0       3
31600.0.0       3
89700.0.0       3
54800.0.0       3
29200.0.0       3
30800.0.0       3
72100.0.0       3
80900.0.0       3
68500.0.0       3
67100.0.0       3
55800.0.0       3
40400.0.0       3
28100.0.0       3
43600.0.0       2
101000.0.0      2
34200.0.0       2
34800.0.0       2
105900.0.0      2
25200.0.0       2
50400.0.0       2
60100.0.0       2
59200.0.0       2
25600.0.0       2
90900.0.0       2
62000.0.0       2
17200.0.0       2
75800.0.0       2
33400.0.0       2
38700.0.0       2
88800.0.0       2
73300.0.0       2
75700.0.0       2
58100.0.0       2
93500.0.0       2
40100.0.0       2
57000.0.0       2
105600.0.0      2
18900.0.0       2
74100.0.0       2
25100.0.0       2
85500.0.0       2
84000.0.0       2
64300.0.0       2
20300.0.0       2
67300.0.0       2
97900.0.0       2
44700.0.0       2
66900.0.0       2
38000.0.0       2
73900.0.0       2
51000.0.0       2
65100.0.0       2
72300.0.0       2
66100.0.0       2
90700.0.0       2
64400.0.0       2
76700.0.0       2
60700.0.0       2
39600.0.0       2
38200.0.0       2
75500.0.0       2
28400.0.0       2
66400.0.0       2
76600.0.0       2
95900.0.0       2
45700.0.0       2
56400.0.0       2
51400.0.0       2
28800.0.0       2
85300.0.0       2
36300.0.0       2
41200.0.0       2
20400.0.0       2
67600.0.0       2
116500.0.0      2
16200.0.0       2
79400.0.0       2
54000.0.0       2
56800.0.0       2
114700.0.0      2
54600.0.0       2
32500.0.0       2
48800.0.0       2
37300.0.0       2
72200.0.0       2
22200.0.0       2
33500.0.0       2
30100.0.0       2
47000.0.0       2
21800.0.0       2
40800.0.0       2
58800.0.0       2
80500.0.0       2
71800.0.0       2
42700.0.0       2
75300.0.0       2
101100.0.0      2
76200.0.0       2
99700.0.0       2
23600.0.0       2
117800.0.0      2
63800.0.0       2
18800.0.0       2
69900.0.0       2
65200.0.0       2
50700.0.0       2
46000.0.0       2
59000.0.0       2
61100.0.0       2
30400.0.0       2
83400.0.0       2
65500.0.0       2
70600.0.0       2
67400.0.0       2
94000.0.0       2
84900.0.0       2
54900.0.0       2
28200.0.0       2
133600.0.0      2
76300.0.0       2
39400.0.0       2
57300.0.0       2
25000.0.0       2
44500.0.0       2
119700.0.0      2
24100.0.0       2
50300.0.0       2
95400.0.0       2
59600.0.0       2
16600.0.0       2
62300.0.0       2
20800.0.0       2
86800.0.0       2
90100.0.0       2
24300.0.0       2
91800.0.0       2
78300.0.0       2
71200.0.0       2
19100.0.0       2
63100.0.0       2
51900.0.0       2
49000.0.0       2
23900.0.0       2
63700.0.0       2
103000.0.0      2
46300.0.0       2
72500.0.0       2
47400.0.0       2
97400.0.0       2
63200.0.0       2
32100.0.0       2
26800.0.0       2
25800.0.0       2
44900.0.0       2
28500.0.0       2
38100.0.0       2
93300.0.0       2
81700.0.0       2
112000.0.0      2
54100.0.0       2
32600.0.0       2
131100.0.0      2
72600.0.0       2
65400.0.0       2
89600.0.0       2
29900.0.0       2
56900.0.0       2
42800.0.0       2
116400.0.0      2
97800.0.0       2
71300.0.0       2
52800.0.0       2
64100.0.0       2
23300.0.0       2
77800.0.0       2
31300.0.0       2
119000.0.0      2
24400.0.0       2
58200.0.0       2
113900.0.0      2
22700.0.0       2
98000.0.0       2
76000.0.0       2
22800.0.0       2
52700.0.0       2
98600.0.0       2
34600.0.0       2
83700.0.0       2
25500.0.0       2
122200.0.0      2
25400.0.0       2
23500.0.0       2
78100.0.0       2
64200.0.0       2
57600.0.0       2
94400.0.0       2
49600.0.0       2
45500.0.0       2
90000.0.0       2
77900.0.0       2
111900.0.0      2
106900.0.0      2
85100.0.0       2
52200.0.0       2
79600.0.0       2
43900.0.0       2
24000.0.0       2
35900.0.0       2
35300.0.0       2
74900.0.0       2
47700.0.0       2
79100.0.0       2
104600.0.0      2
74000.0.0       2
18400.0.0       2
78400.0.0       2
17300.0.0       2
46800.0.0       2
28700.0.0       2
32000.0.0       2
97200.0.0       2
110600.0.0      2
65600.0.0       2
77600.0.0       2
22600.0.0       2
61000.0.0       2
55600.0.0       2
93000.0.0       2
93100.0.0       2
69100.0.0       2
33200.0.0       2
44000.0.0       2
70500.0.0       2
81100.0.0       2
70300.0.0       2
29800.0.0       2
83200.0.0       2
101600.0.0      2
103300.0.0      2
72700.0.0       2
59400.0.0       1
31000.0.0       1
74500.0.0       1
97000.0.0       1
142300.0.0      1
115400.0.0      1
61700.0.0       1
58000.0.0       1
94300.0.0       1
81200.0.0       1
94700.0.0       1
18500.0.0       1
50451.0.0       1
34300.0.0       1
117700.0.0      1
113600.0.0      1
44100.0.0       1
60000.0.0       1
130500.0.0      1
82800.0.0       1
96800.0.0       1
42100.0.0       1
27700.0.0       1
114900.0.0      1
102166.0.0      1
96000.0.0       1
169000.0.0      1
45200.0.0       1
132500.0.0      1
119900.0.0      1
135000.0.0      1
138900.0.0      1
108700.0.0      1
115700.0.0      1
73800.0.0       1
171900.0.0      1
30500.0.0       1
54700.0.0       1
45400.0.0       1
51883.0.0       1
105500.0.0      1
127200.0.0      1
24800.0.0       1
53868.0.0       1
67200.0.0       1
23732.0.0       1
43000.0.0       1
87500.0.0       1
31400.0.0       1
41505.0.0       1
8727.0.0        1
8274.0.0        1
31977.0.0       1
87200.0.0       1
142800.0.0      1
92200.0.0       1
175900.0.0      1
78700.0.0       1
88500.0.0       1
66500.0.0       1
47900.0.0       1
80100.0.0       1
81800.0.0       1
86000.0.0       1
144800.0.0      1
87700.0.0       1
119800.0.0      1
73000.0.0       1
94100.0.0       1
109700.0.0      1
416565.0.0      1
82100.0.0       1
22300.0.0       1
117500.0.0      1
120600.0.0      1
9953.0.0        1
81400.0.0       1
50000.0.0       1
99800.0.0       1
60600.0.0       1
45568.0.0       1
46100.0.0       1
76900.0.0       1
24900.0.0       1
99600.0.0       1
74400.0.0       1
35000.0.0       1
65700.0.0       1
103551.0.0      1
115500.0.0      1
43100.0.0       1
128500.0.0      1
66700.0.0       1
352671.0.0      1
121100.0.0      1
420722.0.0      1
131700.0.0      1
48400.0.0       1
56200.0.0       1
26500.0.0       1
116800.0.0      1
99300.0.0       1
134200.0.0      1
118500.0.0      1
30200.0.0       1
26144.0.0       1
64800.0.0       1
20600.0.0       1
129100.0.0      1
6707.0.0        1
33900.0.0       1
377086.0.0      1
108500.0.0      1
23000.0.0       1
124600.0.0      1
31200.0.0       1
17800.0.0       1
120200.0.0      1
90500.0.0       1
103100.0.0      1
87400.0.0       1
100500.0.0      1
87900.0.0       1
338982.0.0      1
52500.0.0       1
21900.0.0       1
98700.0.0       1
26600.0.0       1
103800.0.0      1
69187.0.0       1
101200.0.0      1
58700.0.0       1
90159.0.0       1
131400.0.0      1
20200.0.0       1
82700.0.0       1
75100.0.0       1
137800.0.0      1
51200.0.0       1
159000.0.0      1
128100.0.0      1
60800.0.0       1
106800.0.0      1
128900.0.0      1
67000.0.0       1
84700.0.0       1
80400.0.0       1
120300.0.0      1
105100.0.0      1
178500.0.0      1
31500.0.0       1
155600.0.0      1
6503.0.0        1
21400.0.0       1
30400.0.0.0     1
9747.0.0        1
111200.0.0      1
78800.0.0       1
76800.0.0       1
127800.0.0      1
51300.0.0       1
85900.0.0       1
39200.0.0       1
103876.0.0      1
17000.0.0       1
327263.0.0      1
116300.0.0      1
118000.0.0      1
100635.0.0      1
384821.0.0      1
15400.0.0       1
59644.0.0       1
145900.0.0      1
48100.0.0       1
79800.0.0       1
18300.0.0       1
55400.0.0       1
98100.0.0       1
137500.0.0      1
89500.0.0       1
100700.0.0      1
102900.0.0      1
10012.0.0       1
128200.0.0      1
65800.0.0       1
134100.0.0      1
135900.0.0      1
78600.0.0       1
73100.0.0       1
76500.0.0       1
316512.0.0      1
104300.0.0      1
62500.0.0       1
107100.0.0      1
84200.0.0       1
47638.0.0       1
71500.0.0       1
109900.0.0      1
47100.0.0       1
49100.0.0       1
26200.0.0       1
71900.0.0       1
22400.0.0       1
53000.0.0       1
96600.0.0       1
319795.0.0      1
102500.0.0      1
125500.0.0      1
129800.0.0      1
100100.0.0      1
83800.0.0       1
80700.0.0       1
125900.0.0      1
73700.0.0       1
90300.0.0       1
128800.0.0      1
69800.0.0       1
41400.0.0       1
107400.0.0      1
55300.0.0       1
86600.0.0       1
133400.0.0      1
106500.0.0      1
63500.0.0       1
325596.0.0      1
37700.0.0       1
118900.0.0      1
90200.0.0       1
102600.0.0      1
10785.0.0       1
66000.0.0       1
109000.0.0      1
11021.0.0       1
99000.0.0       1
6564.0.0        1
89000.0.0       1
86300.0.0       1
100200.0.0      1
51700.0.0       1
85821.0.0       1
35700.0.0       1
45800.0.0       1
91100.0.0       1
89400.0.0       1
100600.0.0      1
36000.0.0       1
101900.0.0      1
154700.0.0      1
15900.0.0       1
128000.0.0      1
93600.0.0       1
8160.0.0        1
85000.0.0       1
119400.0.0      1
73500.0.0       1
27600.0.0       1
373757.0.0      1
81600.0.0       1
81400.0.0.0     1
48200.0.0       1
34179.0.0       1
150100.0.0      1
147700.0.0      1
50900.0.0       1
6917.0.0        1
50600.0.0       1
107800.0.0      1
101700.0.0      1
105800.0.0      1
109800.0.0      1
91600.0.0       1
64000.0.0       1
70400.0.0       1
97700.0.0       1
110200.0.0      1
85200.0.0       1
106100.0.0      1
149900.0.0      1
56300.0.0       1
88600.0.0       1
454609.0.0      1
132200.0.0      1
17400.0.0       1
92400.0.0       1
127000.0.0      1
21600.0.0       1
105200.0.0      1
123800.0.0      1
70200.0.0       1
108600.0.0      1
95200.0.0       1
75200.0.0       1
69500.0.0       1
487848.0.0      1
65000.0.0       1
85600.0.0       1
73600.0.0       1
40200.0.0       1
11493.0.0       1
122928.0.0      1
79900.0.0       1
83500.0.0       1
23100.0.0       1
64700.0.0       1
53900.0.0       1
139300.0.0      1
141000.0.0      1
84400.0.0       1
63400.0.0       1
123400.0.0      1
14600.0.0       1
75400.0.0       1
91900.0.0       1
88300.0.0       1
16900.0.0       1
109600.0.0      1
82600.0.0       1
98900.0.0       1
21100.0.0       1
84800.0.0       1
81300.0.0       1
113100.0.0      1
120100.0.0      1
86700.0.0       1
86900.0.0       1
83000.0.0       1
109300.0.0      1
43800.0.0       1
76400.0.0       1
142400.0.0      1
104500.0.0      1
49700.0.0       1
53100.0.0       1
71700.0.0       1
156200.0.0      1
78000.0.0       1
48624.0.0       1
71000.0.0       1
56000.0.0       1
30600.0.0       1
85800.0.0       1
23400.0.0.0     1
72617.0.0       1
106200.0.0      1
88700.0.0       1
26700.0.0       1
19400.0.0       1
20100.0.0       1
62800.0.0       1
112400.0.0      1
104200.0.0      1
113800.0.0      1
74300.0.0       1
70000.0.0       1
49800.0.0       1
9611.0.0        1
123200.0.0      1
115300.0.0      1
40000.0.0       1
93800.0.0       1
69600.0.0       1
112200.0.0      1
72800.0.0       1
126500.0.0      1
97500.0.0       1
117400.0.0      1
125700.0.0      1
142200.0.0      1
44300.0.0       1
36800.0.0       1
17500.0.0       1
102100.0.0      1
62600.0.0       1
55100.0.0       1
71100.0.0       1
Name: count, dtype: int64

In [6]:
#  Age dirty values

df["age_raw"] = df["age"]

df["age"] = pd.to_numeric(
    df["age"],
    errors="coerce"
)

dirty_age_rows = df[
    df["age"].isna() &
    df["age_raw"].notna()
]

dirty_age_rows[["age_raw"]].drop_duplicates()

       age_raw
109660  58.0.0
238011  38.0.0
315969  32.0.0

In [7]:
# To see NAN value rows in emi eligibility column
df.loc[
    df["emi_eligibility"].isna(),
    ["age", "monthly_salary", "credit_score", "emi_eligibility"]
]

Empty DataFrame
Columns: [age, monthly_salary, credit_score, emi_eligibility]
Index: []

In [9]:
df.loc[
    (df["credit_score"] < 300) |
    (df["credit_score"] > 900)
].head(10)

,age,gender,marital_status,education,monthly_salary,employment_type,years_of_employment,company_type,house_type,monthly_rent,family_size,dependents,school_fees,college_fees,travel_expenses,groceries_utilities,other_monthly_expenses,existing_loans,current_emi_amount,credit_score,bank_balance,emergency_fund,emi_scenario,requested_amount,requested_tenure,emi_eligibility,max_monthly_emi,monthly_salary_raw,age_raw
166,38.0,Female,Married,Post Graduate,95900.0,Private,3.3,MNC,Family,0.0,4,3,8600.0,0.0,7900.0,18400.0,17800.0,No,0.0,1200.0,695300.0,383000.0,Vehicle EMI,482000.0,19,Not_Eligible,23760.0,95900.0,38.0
251,38.0,Male,Married,Post Graduate,59300.0,Private,11.2,Small,Rented,15500.0,4,3,7400.0,16800.0,8900.0,15800.0,8600.0,No,0.0,0.0,39900.0,16800.0,Vehicle EMI,1121000.0,54,Not_Eligible,500.0,59300.0,38.0
290,32.0,Male,Single,Professional,143300.0,Private,0.5,Startup,Rented,35800.0,2,1,5100.0,0.0,13800.0,24500.0,12800.0,Yes,21200.0,999.0,722800.0,225400.0,Home Appliances EMI,22000.0,25,Eligible,10113.6,143300.0,32.0
707,32.0,Male,Single,Professional,87500.0,Private,1.6,Large Indian,Rented,17200.0,2,1,5200.0,0.0,9300.0,21300.0,9200.0,Yes,9400.0,0.0,649800.0,141300.0,Home Appliances EMI,96000.0,30,Eligible,4897.2,87500.0,32.0
763,38.0,Male,Married,Graduate,43400.0,Private,0.6,Startup,Rented,15100.0,4,3,3300.0,0.0,3600.0,12000.0,8100.0,Yes,11600.0,1200.0,320100.0,99500.0,Personal Loan EMI,652000.0,58,Not_Eligible,500.0,43400.0,38.0
846,27.0,Male,Single,Graduate,30900.0,Government,0.5,Small,Family,0.0,2,1,0.0,0.0,2600.0,5400.0,5600.0,Yes,6400.0,999.0,145500.0,60300.0,Home Appliances EMI,50000.0,33,Eligible,3052.0,30900.0,27.0
852,27.0,Male,Married,Graduate,41600.0,Private,1.3,MNC,Rented,8100.0,4,3,0.0,0.0,4600.0,8300.0,7100.0,Yes,9800.0,1200.0,35500.0,8800.0,Home Appliances EMI,99000.0,17,Not_Eligible,828.8,41600.0,27.0
948,32.0,Female,Married,High School,58600.0,Government,1.8,MNC,Rented,14900.0,2,1,0.0,0.0,8000.0,16800.0,9500.0,Yes,7500.0,0.0,124300.0,31900.0,E-commerce Shopping EMI,13000.0,12,Not_Eligible,665.0,58600.0,32.0
1005,27.0,Female,Single,Graduate,55200.0,Self-employed,0.5,Large Indian,Family,0.0,1,0,0.0,0.0,3900.0,10500.0,4500.0,No,0.0,999.0,60600.0,26200.0,Home Appliances EMI,281000.0,6,Not_Eligible,13068.0,55200.0,27.0
1084,48.0,M,Married,High School,54800.0,Private,7.7,MNC,Rented,18700.0,3,2,10400.0,0.0,5500.0,9500.0,7000.0,No,0.0,1200.0,194700.0,97400.0,Vehicle EMI,1357000.0,82,Not_Eligible,1850.0,54800.0,48.0

In [13]:
df.drop(['monthly_salary_raw', 'age_raw'], axis=1, inplace=True)

In [14]:
df.columns

Index(['age', 'gender', 'marital_status', 'education', 'monthly_salary',
       'employment_type', 'years_of_employment', 'company_type', 'house_type',
       'monthly_rent', 'family_size', 'dependents', 'school_fees',
       'college_fees', 'travel_expenses', 'groceries_utilities',
       'other_monthly_expenses', 'existing_loans', 'current_emi_amount',
       'credit_score', 'bank_balance', 'emergency_fund', 'emi_scenario',
       'requested_amount', 'requested_tenure', 'emi_eligibility',
       'max_monthly_emi'],
      dtype='object')

COLUMN           OLD WAY              NEW WAY
────────────────────────────────────────────────────────────

monthly_rent   global median    →   0 if own/family house
                                    renter median if rented

credit_score   global median    →   300 (no history = risky)
               (~680 = good!)       flag column created

bank_balance   global median    →   salary bracket median
                                    (similar earners)
                                    flag column created

emergency_fund global median    →   0 (null = no fund)
                                    flag column created

education      mode (Graduate)  →   'Unknown' category
                                    flag column created

🚩 NEW FLAG COLUMNS ADDED

credit_score_missing    → 1 if credit score was null

bank_balance_missing    → 1 if bank balance was null

emergency_fund_missing  → 1 if emergency fund was null

education_missing       → 1 if education was null

WHY FLAGS MATTER:
Model sees BOTH the filled value AND the flag
It learns: "when flag=1, be more careful"
This is what separates production ML
from notebook ML ✅